### ISSUE TITLE
Inconsistency of versioning

### ISSUE THREAD

**Issue by MawirPL** [RobertBendun/site.old#2]
Hi,

I would like to ask question regarding version of Bendun.cc website. The header has value `bendun(7)`, but in the text below it's mentioned that it's the 6th version of Bendun.cc. Which number is the true version?

Best regards,
True fan of Bendun.cc Aleks

**Comment by RobertBendun** [comment]
This is the 6th version, in the works is 9th version (premiere in a 2 weeks).
The 7 is a referance to man pages convention. Each man page has number up there named "section number". Commands like cat are `cat(1)`, c functions like printf are `printf(3)`.

You can type `man man` in your OS to find out more.

```
The table below shows the section numbers of the manual followed by the types of pages they contain:

       1   Executable programs or shell commands
       2   System calls (functions provided by the kernel)
       3   Library calls (functions within program libraries)
       4   Special files (usually found in /dev)
       5   File formats and conventions, e.g. /etc/passwd
       6   Games
       7   Miscellaneous (including macro packages and conventions), e.g. man(7), groff(7), man-pages(7)
       8   System administration commands (usually only for root)
       9   Kernel routines [Non standard]
```

This is also a consequence of the format that my main page was originally written in - as a man page and converted to html using this tool of mine: https://github.com/RobertBendun/msg.git

**Comment by RobertBendun** [comment]
I found original source! You can view it in man form:

```bash
wget 'https://gist.githubusercontent.com/RobertBendun/80ead82aea2f1ba553d1d40cd3a8c3f6/raw/05c9be3bad64aa58e9e732812caeb02b1e2a0870/index.1'
man ./index.1
```
